language: node_js
node_js:
  - "node"
services:
  - postgresql

before_install:
  - psql -c 'create database travis_ci_test;' -U postgres
env:
  - DATABASE_URL=postgresql://postgres:@localhost/travis_ci_test POSTGRESQLNOSSL=true
